name: Master CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build

    steps:
      - uses: actions/checkout@v2

      # - name: Cache node modules
      #   uses: actions/cache@v2
      #   with:
      #     path: '**/node_modules'
      #     key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-nodemodules-

      # https://github.com/actions/setup-node
      # - name: Install Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: "10.x"

      # - name: Install npm dependencies
      #   run: |
      #     npm install --save && npm install -g twilio-cli

      #- name: npm install and npm run build
      #  run: |
      #    npm ci
      #    npm run build 

      # - name: Run build task for videocall.tutorreach.com
      #   run: |
      #     npm run build
      #     npm test
      #   env:
      #     CI: true


      - name: Deploy ui and to videocall.tutorreach.com
        if: github.ref == 'refs/heads/master'
        run: |
          eval $(ssh-agent -s) 
          ssh-add <(echo "$SSH_PRIVATE_KEY") 
          # List out your new key's fingerprint
          ssh-add -l
          tar zcf /tmp/build.tar.gz --exclude .git -C build/ .
          scp -P 2223 -o stricthostkeychecking=no /tmp/build.tar.gz twiliovideo@${DEVELOPMENT_HOSTNAME}:deploy/backend/
          ssh twiliovideo@${DEVELOPMENT_HOSTNAME} -p 2223 "tar xfz deploy/backend/build.tar.gz -C public_html && exit"
        env:
          DEVELOPMENT_HOSTNAME: 18.132.221.77
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}